name: Infra Plan
description: Uses testnet-deploy to run a 'terraform plan' against an existing network
inputs:
  network-name:
    description: The name of the network
    required: true
  provider:
    description: The cloud provider. Accepts 'aws' or 'digital-ocean'.
    required: true

runs:
  using: composite
  steps:
    - name: Infra plan
      env:
        NETWORK_NAME: ${{ inputs.network-name }}
        PROVIDER: ${{ inputs.provider }}
      shell: bash
      run: |
        set -e
        cd sn-testnet-deploy
        testnet-deploy plan --name $NETWORK_NAME --provider $PROVIDER
