name: Fund Uploaders
description: Use testnet-deploy to fund the uploaders for the environment
inputs:
  network-name:
    description: The name of the network
    required: true
  repeat:
    description: >
      Set to fund each wallet multiple times. For example, if you want to put 5 coins in each
      wallet, use 4 as the value.
    default: 0
    type: number

runs:
  using: composite
  steps:
    - name: start faucet
      env:
        NETWORK_NAME: ${{ inputs.network-name }}
      shell: bash
      run: |
        set -e

        cd sn-testnet-deploy
        testnet-deploy faucet start --name $NETWORK_NAME

    - name: fund uploaders
      env:
        NETWORK_NAME: ${{ inputs.network-name }}
        REPEAT: ${{ inputs.repeat }}
      shell: bash
      run: |
        set -e

        cd sn-testnet-deploy
        testnet-deploy faucet fund-uploaders --name $NETWORK_NAME --repeat $REPEAT

    - name: stop faucet
      env:
        NETWORK_NAME: ${{ inputs.network-name }}
      shell: bash
      run: |
        set -e

        cd sn-testnet-deploy
        testnet-deploy faucet stop --name $NETWORK_NAME
