name: Start Uploaders
description: Use testnet-deploy to start the uploaders for the environment
inputs:
  network-name:
    description: The name of the network
    required: true

runs:
  using: composite
  steps:
    - name: start uploaders
      env:
        NETWORK_NAME: ${{ inputs.network-name }}
      shell: bash
      run: |
        set -e

        cd sn-testnet-deploy
        testnet-deploy uploaders start --name $NETWORK_NAME
