name: Start Downloaders
description: Use testnet-deploy to start the downloaders for the environment
inputs:
  network-name:
    description: The name of the network
    required: true

runs:
  using: composite
  steps:
    - name: start downloaders
      env:
        NETWORK_NAME: ${{ inputs.network-name }}
      shell: bash
      run: |
        set -e

        cd sn-testnet-deploy
        testnet-deploy clients start-downloaders --name $NETWORK_NAME
